### ISSUE TITLE
All retries of `HTTPLimitsIntegrationTest` fail on native

### ISSUE THREAD

**Issue by ivansenic** [stargate/jsonapi#266]
```
INFO  [main] 2023-03-15 12:24:17,187 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:17,187 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:17,189 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:17,189 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:17,191 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:17,191 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:17,634 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:17,634 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:17,635 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:17,635 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:17,636 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:17,636 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:18,057 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:18,057 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:18,058 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:18,059 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:18,060 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:18,060 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:18,382 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:18,382 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:18,384 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:18,384 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:18,388 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:18,389 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:18,781 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:18,782 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:18,784 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:18,784 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [main] 2023-03-15 12:24:18,785 DefaultRequestDirector.java:690 - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:9080: Broken pipe
INFO  [main] 2023-03-15 12:24:18,785 DefaultRequestDirector.java:700 - Retrying request to {}->http://localhost:9080
INFO  [docker-java-stream--1256185243] 2023-03-15 12:24:18,815 Slf4jLogConsumer.java:68 - [CASSANDRA] STDOUT: INFO  [CoreThread-0] 2023-03-15 12:24:18,802  QueryProcessor.java:426 - Executing DDL statement 'DROP KEYSPACE IF EXISTS "ks6151669758756249"' from client IP /172.18.0.1:42584 by user #<User anonymous>
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 6.838 s <<< FAILURE! - in io.stargate.sgv2.jsonapi.api.v1.HTTPLimitsIntegrationTest
Error:  io.stargate.sgv2.jsonapi.api.v1.HTTPLimitsIntegrationTest.tryToSendTooBigInsert  Time elapsed: 0.404 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Test execution #5 (of up to 5 with at least 1 successes) failed ~> test fails - see cause for details
	at org.junitpioneer.jupiter.RetryingTestExtension$FailedTestRetrier.failed(RetryingTestExtension.java:158)
	at org.junitpioneer.jupiter.RetryingTestExtension.handleTestExecutionException(RetryingTestExtension.java:62)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestExecutionExceptionHandlers$8(TestMethodTestDescriptor.java:231)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.invokeExecutionExceptionHandlers(JupiterTestDescriptor.java:123)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.invokeExecutionExceptionHandlers(JupiterTestDescriptor.java:110)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestExecutionExceptionHandlers(TestMethodTestDescriptor.java:230)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:222)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
```

**Comment by ivansenic** [comment]
Getting on my nerves, will try to fix this.
